[2023-04-11 22:10:19,422] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:10:19] "OPTIONS /profissional HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:10:19,439] WARNING put_profissional() L393  Erro ao editar o profissional com ID #'3', Não foi possível editar o profissional :/<method-wrapper '__str__' of AttributeError object at 0x000002C4E181A730> - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L393 
[2023-04-11 22:10:19,440] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:10:19] "[35m[1mPUT /profissional HTTP/1.1[0m" 500 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:13:11,437] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:13:11] "OPTIONS /profissional HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:13:11,458] WARNING put_profissional() L393  Erro ao editar o profissional com ID #'3', Não foi possível editar o profissional :/<method-wrapper '__str__' of AttributeError object at 0x000002C4E181A730> - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L393 
[2023-04-11 22:13:11,459] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:13:11] "[35m[1mPUT /profissional HTTP/1.1[0m" 500 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:13:54,563] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:13:54] "GET /profissionais HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:13:57,907] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:13:57] "OPTIONS /profissional HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:13:57,920] WARNING put_profissional() L393  Erro ao editar o profissional com ID #'3', Não foi possível editar o profissional :/<method-wrapper '__str__' of AttributeError object at 0x000002C4E181A730> - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L393 
[2023-04-11 22:13:57,921] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:13:57] "[35m[1mPUT /profissional HTTP/1.1[0m" 500 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:14:04,146] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:14:04] "OPTIONS /profissional HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:14:04,159] WARNING put_profissional() L393  Erro ao editar o profissional com ID #'3', Não foi possível editar o profissional :/<method-wrapper '__str__' of AttributeError object at 0x000002C4E181A730> - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L393 
[2023-04-11 22:14:04,160] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:14:04] "[35m[1mPUT /profissional HTTP/1.1[0m" 500 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:14:41,807] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:14:41] "GET /profissionais HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:14:49,765] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:14:49] "OPTIONS /profissional HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:14:49,780] WARNING put_profissional() L393  Erro ao editar o profissional com ID #'3', Não foi possível editar o profissional :/<method-wrapper '__str__' of AttributeError object at 0x000002C4E181A730> - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L393 
[2023-04-11 22:14:49,781] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:14:49] "[35m[1mPUT /profissional HTTP/1.1[0m" 500 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:17:41,790] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.86:5000 (Press CTRL+C to quit) - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:17:47,749] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:17:47] "OPTIONS /profissional HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:17:47,784] WARNING put_profissional() L393  Erro ao editar o profissional com ID #'3' e profissional Juniors, Não foi possível editar o profissional :/<method-wrapper '__str__' of AttributeError object at 0x000001A742969FC0> - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L393 
[2023-04-11 22:17:47,786] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:17:47] "[35m[1mPUT /profissional HTTP/1.1[0m" 500 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:18:32,957] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.86:5000 (Press CTRL+C to quit) - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:18:39,813] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:18:39] "OPTIONS /profissional HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:18:39,840] ERROR log_exception() L1449 Exception on /profissional [PUT] - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\flask\app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'put_profissional' did not return a valid response. The function either returned None or ended without a return statement.
[2023-04-11 22:18:39,842] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:18:39] "[35m[1mPUT /profissional HTTP/1.1[0m" 500 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:19:15,908] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.86:5000 (Press CTRL+C to quit) - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:19:19,533] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:19:19] "OPTIONS /profissional HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:19:19,567] WARNING put_profissional() L376  Erro ao editar o profissional 'Juniors', Profissional já cadastrado na base - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L376 
[2023-04-11 22:19:19,568] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:19:19] "[31m[1mPUT /profissional HTTP/1.1[0m" 400 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:19:37,081] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:19:37] "OPTIONS /profissional HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:19:37,095] WARNING put_profissional() L376  Erro ao editar o profissional 'Juniors', Profissional já cadastrado na base - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L376 
[2023-04-11 22:19:37,096] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:19:37] "[31m[1mPUT /profissional HTTP/1.1[0m" 400 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 22:19:45,668] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 22:19:45] "GET /profissionais HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
